### ISSUE TITLE
Breakage with custom log path in ansible.cfg

### ISSUE THREAD

**Issue by wr0ngway** [neillturner/kitchen-ansible#113]
If I have an ansible.cfg which sets the log path like so:

```
log_path            = ./logs/ansible.log
```

Then `kitchen converge` fails with the following error:

```
       Transferring files to <default-ubuntu-1404>
       Going to invoke ansible-playbook with: ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vvv   --vault-password-file=/tmp/kitchen/vaultpw    /tmp/kitchen/default.yml
       Traceback (most recent call last):
         File "/usr/bin/ansible-playbook", line 44, in <module>
           import ansible.playbook
         File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 18, in <module>
           import ansible.inventory
         File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 26, in <module>
           from ansible.inventory.ini import InventoryParser
         File "/usr/lib/pymodules/python2.7/ansible/inventory/ini.py", line 21, in <module>
           from ansible.inventory.host import Host
         File "/usr/lib/pymodules/python2.7/ansible/inventory/host.py", line 19, in <module>
           from ansible import utils
         File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 29, in <module>
           from ansible.utils.display_functions import *
         File "/usr/lib/pymodules/python2.7/ansible/utils/display_functions.py", line 22, in <module>
           from ansible.callbacks import display
         File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 42, in <module>
           logging.basicConfig(filename=path, level=logging.DEBUG, format='%(asctime)s %(name)s %(message)s')
         File "/usr/lib/python2.7/logging/__init__.py", line 1532, in basicConfig
           hdlr = FileHandler(filename, mode)

       StreamHandler.__init__(self, self._open())
         File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
       stream = open(self.baseFilename, self.mode)
       : [Errno 2] No such file or directory: '/home/kitchen/logs/ansible.log'
```

Not sure why it is looking for the log file in `/home/kitchen/logs/ansible.log` instead of `/tmp/kitchen/logs/ansible.log` (the logs directory is part of our ansible repo)

If I remove the `log_path` line from ansible.cfg, things work as expected.

**Comment by neillturner** [comment]
well i guess the current directory when run ansible-playbook is /home/kitchen. if 
you add pwd to the ansible_command you could prove it. 
. doesn't mean /tmp/kitchen i think.

**Comment by wr0ngway** [comment]
Right, but kitchen puts all my ansible files in /tmp/kitchen, so I'm guessing there is some disconnect there if it is running from the home directory.  I'll try changing the ansible command to cd to /tmp/kitchen as a workaround, but maybe this should be done by default?

**Comment by neillturner** [comment]
we are doing remote ssh so it is the home directory of the ssh user.

**Comment by neillturner** [comment]
ok I will add a cd /tmp/kitchen  when there is a ansible.cfg file.

**Comment by neillturner** [comment]
I attempted to implement this in version 0.0.34 but could not get it to work. So will look at it a bit more in the future.

**Comment by neillturner** [comment]
closing.its beyond the scope of the plugin to start reading the ansible ansible.cfg file
