### ISSUE TITLE
 Could not load the 'ansible_playbook' provisioner from the load path. 

### ISSUE THREAD

**Issue by weldpua2008** [neillturner/kitchen-ansible#162]
##### ISSUE TYPE
 - Bug Report

#####  TEST KITCHEN VERSION
kitchen version
```
Test Kitchen version 1.8.0
```
##### OS / ENVIRONMENT

lsb_release -a

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        8.1
Codename:       jessie
```

##### SUMMARY

cat .kitchen/logs/kitchen.log
```
I, [2016-05-22T11:07:56.131565 #21608]  INFO -- Kitchen: -----> Starting Kitchen (v1.8.0)
E, [2016-05-22T11:07:56.209488 #21608] ERROR -- Kitchen: ------Exception-------
E, [2016-05-22T11:07:56.209578 #21608] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2016-05-22T11:07:56.209604 #21608] ERROR -- Kitchen: Message: Could not load the 'ansible_playbook' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
E, [2016-05-22T11:07:56.209620 #21608] ERROR -- Kitchen: ---Nested Exception---
E, [2016-05-22T11:07:56.209633 #21608] ERROR -- Kitchen: Class: Gem::LoadError
E, [2016-05-22T11:07:56.209654 #21608] ERROR -- Kitchen: Message: Unable to activate kitchen-ansible-0.42.4, because net-ssh-4.0.0.alpha4 conflicts with net-ssh (~> 3.0)
```

##### STEPS TO REPRODUCE

```
apt-get install ruby-dev -y
apt-get install gem rubygems build-essential -y
gem install kitchen-lxc
gem install kitchen-vagrant
gem install kitchen-ansible
```

cat .kitchen.yml

```
---
#driver:
#  name:
driver_plugin: lxc


#provisioner:
#  name: chef_solo
provisioner:
  name: ansible_playbook
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: true
#  ansible_version: latest
  require_ansible_omnibus: true
  ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh


#platforms:
#  - name: ubuntu-14.04
#  - name: centos-7.2
platforms:
- name: ubuntu
  driver_config:
    username: kitchen # defaults to "root"
    password: kitchen # defaults to "root"

suites:
  - name: default
    run_list:
    attributes:
```

##### ACTUAL RESULTS

kitchen test

```
-----> Starting Kitchen (v1.8.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ansible_playbook' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

cat .kitchen/logs/kitchen.log
```
I, [2016-05-22T11:17:48.094625 #23088]  INFO -- Kitchen: -----> Starting Kitchen (v1.8.0)
E, [2016-05-22T11:17:48.168888 #23088] ERROR -- Kitchen: ------Exception-------
E, [2016-05-22T11:17:48.168943 #23088] ERROR -- Kitchen: Class: Kitchen::ClientError
E, [2016-05-22T11:17:48.168962 #23088] ERROR -- Kitchen: Message: Could not load the 'ansible_playbook' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
E, [2016-05-22T11:17:48.169011 #23088] ERROR -- Kitchen: ---Nested Exception---
E, [2016-05-22T11:17:48.169033 #23088] ERROR -- Kitchen: Class: Gem::LoadError
E, [2016-05-22T11:17:48.169055 #23088] ERROR -- Kitchen: Message: Unable to activate kitchen-ansible-0.42.4, because net-ssh-4.0.0.alpha4 conflicts with net-ssh (~> 3.0)
E, [2016-05-22T11:17:48.169069 #23088] ERROR -- Kitchen: ------Backtrace-------
E, [2016-05-22T11:17:48.169081 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:48:in `rescue in for_plugin'
E, [2016-05-22T11:17:48.169093 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:40:in `for_plugin'
E, [2016-05-22T11:17:48.169105 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:284:in `new_provisioner'
E, [2016-05-22T11:17:48.169116 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:247:in `new_instance'
E, [2016-05-22T11:17:48.169128 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:139:in `block in build_instances'
E, [2016-05-22T11:17:48.169139 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `map'
E, [2016-05-22T11:17:48.169151 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `with_index'
E, [2016-05-22T11:17:48.169213 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `build_instances'
E, [2016-05-22T11:17:48.169245 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:114:in `instances'
E, [2016-05-22T11:17:48.169258 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2016-05-22T11:17:48.169270 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2016-05-22T11:17:48.169282 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/test.rb:43:in `block in call'
E, [2016-05-22T11:17:48.169294 #23088] ERROR -- Kitchen: /usr/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-05-22T11:17:48.169306 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/test.rb:41:in `call'
E, [2016-05-22T11:17:48.169318 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:56:in `perform'
E, [2016-05-22T11:17:48.169329 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:227:in `test'
E, [2016-05-22T11:17:48.169341 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-05-22T11:17:48.169353 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-05-22T11:17:48.169364 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:321:in `invoke_task'
E, [2016-05-22T11:17:48.169376 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-05-22T11:17:48.169388 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-05-22T11:17:48.169401 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `block in <top (required)>'
E, [2016-05-22T11:17:48.169412 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/errors.rb:154:in `with_friendly_errors'
E, [2016-05-22T11:17:48.169435 #23088] ERROR -- Kitchen: /var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `<top (required)>'
E, [2016-05-22T11:17:48.169450 #23088] ERROR -- Kitchen: /usr/local/bin/kitchen:23:in `load'
E, [2016-05-22T11:17:48.169464 #23088] ERROR -- Kitchen: /usr/local/bin/kitchen:23:in `<main>'
E, [2016-05-22T11:17:48.169476 #23088] ERROR -- Kitchen: ----------------------
```
kitchen diagnose --all
```
---
timestamp: 2016-05-22 08:18:27 UTC
kitchen_version: 1.8.0
plugins:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'ansible_playbook' provisioner
      from the load path. Please ensure that your provisioner is installed as a gem
      or included in your Gemfile if using Bundler.>"
    message: Could not load the 'ansible_playbook' provisioner from the load path.
      Please ensure that your provisioner is installed as a gem or included in your
      Gemfile if using Bundler.
    backtrace:
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:48:in
      `rescue in for_plugin'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:40:in
      `for_plugin'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:284:in `new_provisioner'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:247:in `new_instance'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:139:in `block
      in build_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `map'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `with_index'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `build_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:114:in `instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:115:in `filtered_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:145:in `parse_subcommand'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:56:in `perform'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:136:in `diagnose'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:321:in `invoke_task'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `block in <top
      (required)>'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/errors.rb:154:in `with_friendly_errors'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `<top (required)>'"
    - "/usr/local/bin/kitchen:23:in `load'"
    - "/usr/local/bin/kitchen:23:in `<main>'"
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/root/tests/.kitchen.yml"
    raw_data:
      driver_plugin: lxc
      provisioner:
        name: ansible_playbook
        roles_path: roles
        require_ansible_repo: true
        ansible_verbose: true
        require_ansible_omnibus: true
        ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      platforms:
      - name: ubuntu
        driver_config:
          username: kitchen
          password: kitchen
      suites:
      - name: default
        run_list:
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver_plugin: lxc
      provisioner:
        name: ansible_playbook
        roles_path: roles
        require_ansible_repo: true
        ansible_verbose: true
        require_ansible_omnibus: true
        ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      platforms:
      - name: ubuntu
        driver_config:
          username: kitchen
          password: kitchen
      suites:
      - name: default
        run_list:
        attributes:
instances:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'ansible_playbook' provisioner
      from the load path. Please ensure that your provisioner is installed as a gem
      or included in your Gemfile if using Bundler.>"
    message: Could not load the 'ansible_playbook' provisioner from the load path.
      Please ensure that your provisioner is installed as a gem or included in your
      Gemfile if using Bundler.
    backtrace:
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:48:in
      `rescue in for_plugin'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner.rb:40:in
      `for_plugin'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:284:in `new_provisioner'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:247:in `new_instance'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:139:in `block
      in build_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `map'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `with_index'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:138:in `build_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/config.rb:114:in `instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:115:in `filtered_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:145:in `parse_subcommand'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:56:in `perform'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:136:in `diagnose'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/cli.rb:321:in `invoke_task'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'"
    - "/var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `block in <top
      (required)>'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/errors.rb:154:in `with_friendly_errors'"
    - "/var/lib/gems/2.1.0/gems/test-kitchen-1.8.0/bin/kitchen:13:in `<top (required)>'"
    - "/usr/local/bin/kitchen:23:in `load'"
    - "/usr/local/bin/kitchen:23:in `<main>'"
```

**Comment by neillturner** [comment]
typically you get this error with ruby cannot find the kitchen-ansible gem 
what does a 'gem list' command should 
also if you run kitchen converge xxxx -l debug 
you get more debug info

**Comment by neillturner** [comment]
closing ssh dependency relaxed in version 0.42.5

**Comment by wohlben** [comment]
> closing ssh dependency relaxed in version 0.42.5

mmh~ did you revert it? the same line exists in version 44.2 as well.
though changing it didn't help me... i went back to my previous version (40.1) and it works again.

**Comment by neillturner** [comment]
its only relaxed if you have ruby version >= '2.0'  so if you are running ruby 1.x it will install net-ssh 2.x. 
assuming you have ruby 2.x then the condition is 
  net_ssh ~> 3 
so if any net_ssh 3.x version is installed it will use it. 
If you remove all the net_ssh gems 
and then install kitchen-ansible should get the latest one which is net-ssh 4.x

**Comment by wohlben** [comment]
i'm using 2.1, so _the plot thickens_ ^^
i now have both kitchen-ansible versions installed though... 
i could reprovision a new VM to isolate the error, but i don't really know what steps i should take...

`ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]
`

`gem list
artifactory (2.3.2)
bigdecimal (1.2.4)
faraday (0.9.2)
fast_gettext (0.9.2)
gem2rpm (0.10.1)
highline (2.0.0.pre.develop.6)
io-console (0.4.2)
json (1.8.1)
kitchen-ansible (0.44.2, 0.40.1)
kitchen-sync (2.1.1)
kitchen-vagrant (0.20.0)
librarian (0.1.2)
librarian-ansible (3.0.1)
minitest (4.7.5)
mixlib-install (1.0.13)
mixlib-shellout (2.2.6)
mixlib-versioning (1.1.0)
multipart-post (2.0.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.0.0.alpha4, 3.2.0)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
ruby-dbus (0.9.3)
safe_yaml (1.0.4)
test-kitchen (1.10.0)
test-unit (2.1.2.0)
thor (0.19.1)
`

**Comment by wohlben** [comment]
ah, i should also mention that i tried 

*   removing all kitchen-ansible
*   removing all net-ssh
*   reinstalling kitchen-ansible 0.44.2
*   removing newly installed net-ssh 3.20

problem persisted.

**Comment by neillturner** [comment]
well semantic version should allow any version of net-ssh >= 3  
  net-ssh ~> 3 
but i will change it back to 
   net-ssh >= 3.0 
which should be the same thing.
It maybe because this is an alpha version i.e. 4.0.0.alpha4  
that semantic versioning  treats it differently so maybe >=3.0 is true but ~> 3 is not.
I'll change it. this net-ssh gem is poorly versioned they should be handling this issue about versions not working in certain ruby version not me. I should not have to put in these dependencies!!!l

**Comment by neillturner** [comment]
returned it back to 
  net-ssh ~> 3.0 
in 0.44.4

**Comment by iknite** [comment]
```
E, [2017-02-14T10:41:24.866395 #4341] ERROR -- Kitchen: ----End Backtrace-----
E, [2017-02-14T10:41:24.866407 #4341] ERROR -- Kitchen: ---Nested Exception---
E, [2017-02-14T10:41:24.866420 #4341] ERROR -- Kitchen: Class: Gem::ConflictError
E, [2017-02-14T10:41:24.866435 #4341] ERROR -- Kitchen: Message: Unable to activate kitchen-ansible-0.45.9, because net-ssh-4.0.1 conflicts with net-ssh (~> 3)
E, [2017-02-14T10:41:24.866448 #4341] ERROR -- Kitchen: ----------------------
```
Still a problem with `kitchen-ansible-0.45.9` in `ruby 2.4.0p0`

Can't it be `(>3, <4)`?

**Comment by neillturner** [comment]
relaxed it further in version 0.45.10

**Comment by rchenv** [comment]
I still got the same error with:
net-ssh (4.1.0)
test-kitchen (1.16.0)
kitchen-ansible (0.46.3)

how to fix? Thanks.
