### ISSUE TITLE
travis-ci + docker + ansible 2.0

### ISSUE THREAD

**Issue by steenzout** [neillturner/kitchen-ansible#178]
When using the pip install process and ansible 2.x version the setup is not quite right.

Example of this can be found [here](https://travis-ci.org/saucelabs-ansible/packer/builds/134774805).

On the link you can see ansible 1.9.x tests are working perfectly while 2.x are failing.

```
ERROR! Unexpected Exception: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'))
the full traceback was:

Traceback (most recent call last):
 File "/usr/local/bin/ansible-playbook", line 73, in <module>
   mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
 File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 30, in <module>
   from ansible.executor.playbook_executor import PlaybookExecutor
 File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 27, in <module>
   from ansible.executor.task_queue_manager import TaskQueueManager
 File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
   from ansible.executor.play_iterator import PlayIterator
 File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
   from ansible.playbook.block import Block
 File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
   from ansible.playbook.play import Play
 File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
   from ansible.playbook.base import Base
 File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 35, in <module>
   from ansible.parsing.dataloader import DataLoader
 File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 32, in <module>
   from ansible.parsing.vault import VaultLib
 File "/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py", line 67, in <module>
   from cryptography.hazmat.primitives.hashes import SHA256 as c_SHA256
 File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/hashes.py", line 15, in <module>
   from cryptography.hazmat.backends.interfaces import HashBackend
 File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
   import pkg_resources
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
   working_set = WorkingSet._build_master()
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
   return cls._build_from_requirements(__requires__)
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
   dists = ws.resolve(reqs, Environment())
 File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
   raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'))
```

**Comment by steenzout** [comment]
I'll be providing a patch for this shortly...

**Comment by steenzout** [comment]
for reference: [ansible/ansible issue #16015](https://github.com/ansible/ansible/issues/16015).
