### ISSUE TITLE
Error in converge: SCP upload failed

### ISSUE THREAD

**Issue by davejlong** [neillturner/kitchen-ansible#180]
When I run `kitchen converge -l debug` on my project, I get the following error output:

```
$ kitchen converge -l debug
...
D      [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/david/Projects/rudys/provisioning/.kitchen/kitchen-vagrant/kitchen-provisioning-appserver-centos-72/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"]}>
D      sudo -E rm -rf /tmp/kitchen/modules /tmp/kitchen/roles /tmp/kitchen/group_vars /tmp/kitchen/host_vars; mkdir -p /tmp/kitchen
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/david/Projects/rudys/provisioning/.kitchen/kitchen-vagrant/kitchen-provisioning-appserver-centos-72/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sudo -E rm -rf /tmp/kitchen/modules /tmp/kitchen/roles /tmp/kitchen/group_vars /tmp/kitchen/host_vars; mkdir -p /tmp/kitchen)
       Transferring files to <appserver-centos-72>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      Cleaning up local sandbox in /var/folders/m6/nh705mtj2j95kmrw1qk387ww0000gn/T/appserver-centos-72-sandbox-20160602-62084-bhcnbu
>>>>>> Converge failed on instance <appserver-centos-72>.
>>>>>> Please see .kitchen/logs/appserver-centos-72.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SCP upload failed (open failed (1))
>>>>>> ----------------------
D      Converge failed on instance <appserver-centos-72>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <appserver-centos-72>.  Please see .kitchen/logs/appserver-centos-72.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:76:in `rescue in call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:79:in `call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:478:in `block in action'
D      /Users/david/.rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:477:in `action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:369:in `converge_action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `each'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:138:in `converge'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `public_send'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `run_action_in_thread'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SCP upload failed (open failed (1))
D      ----------------------
D      ------Backtrace-------
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:76:in `rescue in call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:79:in `call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:478:in `block in action'
D      /Users/david/.rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:477:in `action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:369:in `converge_action'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `each'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:138:in `converge'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `public_send'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `run_action_in_thread'
D      /Users/david/.gem/ruby/2.3.1/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

This is my `.kitchen.yml` file:

```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: site.yml

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: appserver
    provisioner:
      hosts: appserver
```

And this is the tree for my build:

```
$ tree .
.
├── Gemfile
├── Gemfile.lock
├── appserver.yml
├── group_vars
├── host_vars
├── hosts
├── roles
│   ├── common
│   │   ├── handlers
│   │   │   └── main.yml
│   │   ├── tasks
│   │   │   └── main.yml
│   │   └── templates
│   └── ruby
│       ├── handlers
│       │   └── main.yml
│       ├── tasks
│       │   ├── main.yml
│       │   └── ruby-install.yml
│       └── templates
├── site.yml
└── test
    └── integration
        └── appserver

14 directories, 10 files
```

**Comment by davejlong** [comment]
It looks like my issue may be related to test-kitchen/test-kitchen#1035. Closing this issue out.
