### ISSUE TITLE
Test run fails when trying to create hosts file

### ISSUE THREAD

**Issue by proffalken** [neillturner/kitchen-ansible#195]
I have the following ~/.kitchen/config.yml file:

```
---
driver:
  name: ec2
  aws_ssh_key_id: test-kitchen
  region: eu-central-1
  availability_zone: a
  subnet_id: <SUBNET-ID>
  instance_type: m3.medium
  associate_public_ip: true
  security_group_ids: ["<SG ID>"]
  interface: public
  tags:
    Created-By: test-kitchen
    Source: DevOpsGuys-MattWallace (www.devopsguys.com)

transport:
  ssh_key: ~/.ssh/test-kitchen
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  enable_yum_repo: true
  require_ansible_repo: true
  ansible_verbose: true
  ansible_verbosity: 4

verifier:
  ruby_bindir: '/usr/bin'

```

with the following role/.kitchen.yml file:

```---
platforms:
  - name: debian-8
    transport:
      username: admin
    driver:
      tags:
        Name: ansible-test-kitchen-role-baselinesecurity-debian-8
        CreatedBy: TestKitchen
        TestKitchenRole: baselinesecurity
        TestKitchenPlatform: debian-8
  - name: centos-7
    transport:
      username: centos
    verifier:
      bundler_path: /opt/rh/ruby200/root/usr/local/bin
      rspec_path: /opt/rh/ruby200/root/usr/local/bin
    driver:
      tags:
        Name: ansible-test-kitchen-role-baselinesecurity-centos-7
        CreatedBy: TestKitchen
        TestKitchenRole: baselinesecurity
        TestKitchenPlatform: centos-7
  - name: ubuntu-16.04
    transport:
      username: ubuntu
    provisioner:
      require_ansible_omnibus: false
    driver:
      tags:
        Name: ansible-test-kitchen-role-baselinesecurity-ubuntu-1604
        CreatedBy: TestKitchen
        TestKitchenRole: baselinesecurity
        TestKitchenPlatform: ubuntu-16.04

suites:
  - name: baseline_security
    verifier:
      patterns:
        - "roles/*/test/integration/baseline_security/serverspec/*_spec.rb"

provisioner:
  name: ansible_playbook
  hosts: all
  requirements_path: test/requirements.yml
  require_ansible_omnibus: true
  require_ruby_for_busser: true
  require_chef_for_busser: false

verifier:
  name: serverspec
  sudo_path: true
```

I'm running the following software versions:

   * test-kitchen: 1.9.0
   * kitchen-ec2: 1.0.0
   * kitchen-ansible: 0.43.0
   * kitchen-verifier-serverspec: 0.5.1

When I run kitchen test -l debug ubuntu, I get the following output:

```
15:13 $ kitchen test -l debug ubuntu
-----> Starting Kitchen (v1.9.0)
-----> Cleaning up any prior instances of <baseline-security-ubuntu-1604>
-----> Destroying <baseline-security-ubuntu-1604>...
       EC2 instance <i-410e8bfc> destroyed.
       Finished destroying <baseline-security-ubuntu-1604> (0m5.57s).
-----> Testing <baseline-security-ubuntu-1604>
-----> Creating <baseline-security-ubuntu-1604>...
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      platform name ubuntu-16.04 appears to be a standard platform. Searching for ubuntu 16.04 ...
D      Searching for images matching {"owner-id"=>"099720109477", "name"=>"ubuntu/images/*/ubuntu-*-16.04*"} ...
D      Search returned 15 images:
D      - ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160721: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2016-07-22T23:02:21.000Z
D      - ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160627: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2016-06-28T16:28:05.000Z
D      - ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160610: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2016-06-13T22:21:15.000Z
D      - ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160516.1: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2016-05-17T20:17:06.000Z
D      - ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160420.3: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: ebs gp2, Created: 2016-04-21T04:07:24.000Z
D      - ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20160721: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: instance-store, Created: 2016-07-22T21:44:14.000Z
D      - ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20160627: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: instance-store, Created: 2016-06-28T15:12:18.000Z
D      - ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20160610: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: instance-store, Created: 2016-06-13T21:09:32.000Z
D      - ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20160516.1: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: instance-store, Created: 2016-05-17T18:48:04.000Z
D      - ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20160420.3: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: hvm, Storage: instance-store, Created: 2016-04-21T02:45:00.000Z
D      - ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160721: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: paravirtual, Storage: ebs gp2, Created: 2016-07-22T23:02:17.000Z
D      - ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160627: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: paravirtual, Storage: ebs gp2, Created: 2016-06-28T16:28:00.000Z
D      - ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160610: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: paravirtual, Storage: ebs gp2, Created: 2016-06-13T22:21:11.000Z
D      - ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160516.1: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: paravirtual, Storage: ebs gp2, Created: 2016-05-17T20:16:59.000Z
D      - ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160420.3: Detected ubuntu 16.04 x86_64.  Architecture: x86_64, Virtualization: paravirtual, Storage: ebs gp2, Created: 2016-04-21T04:07:12.000Z
D      Creating EC2 instance in region eu-central-1 with properties:
D      - instance_type = "m3.medium"
D      - ebs_optimized = false
D      - image_id = "ami-cbee1aa4"
D      - key_name = "test-kitchen"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"eu-central-1a"}
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>true, :delete_on_termination=>true, :subnet_id=>"subnet-3506f55d", :groups=>["sg-5e873436"]}]
       Instance <i-710e8bcc> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-710e8bcc> created.
       Waited 0/300s for instance <i-710e8bcc> to become ready.
       Waited 5/300s for instance <i-710e8bcc> to become ready.
       Waited 10/300s for instance <i-710e8bcc> to become ready.
       Waited 15/300s for instance <i-710e8bcc> to become ready.
       Waited 20/300s for instance <i-710e8bcc> to become ready.
       EC2 instance <i-710e8bcc> ready.
D      [SSH] shutting previous connection ubuntu@52.59.122.22<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"]}>
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"]}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 52.59.125.121:22>)
       Waiting for SSH service on 52.59.125.121:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}> (echo '[SSH] Established')
       [SSH] Established
D      Using sudo_command='sudo -E' for ohai hints
D      [SSH] reusing existing connection ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}> (sudo -E mkdir -p /etc/chef/ohai/hints; sudo -E touch /etc/chef/ohai/hints/ec2.json)
D      ec2:create '52.59.125.121'
       Finished creating <baseline-security-ubuntu-1604> (1m51.22s).
-----> Converging <baseline-security-ubuntu-1604>...
       Preparing files for transfer
D      Creating local sandbox in /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id
D      Creating local sandbox in /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id
       Preparing playbook
D      Copying playbook from /home/mmw/dog_ansible/roles/baseline_security/test/integration/baseline_security/default.yml to /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id/default.yml
       Preparing inventory
       Preparing modules
       nothing to do for modules
       Preparing roles
D      Using roles from ../
       Preparing ansible.cfg file
       Empty ansible.cfg generated
       Preparing group_vars
       nothing to do for group_vars
       Preparing additional_copy_path
       Preparing host_vars
       nothing to do for host_vars
       Preparing hosts file
D      Using host from all
D      Cleaning up local sandbox in /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id
D      [SSH] shutting previous connection ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
D      [SSH] closing connection to ubuntu@52.59.125.121<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>10, :keys_only=>true, :keys=>["/home/mmw/.ssh/test-kitchen"], :auth_methods=>["publickey"], :user=>"ubuntu"}>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
D      ----------------------
D      ------Backtrace-------
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:179:in `run_action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command/test.rb:45:in `block in call'
D      /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command/test.rb:41:in `call'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/cli.rb:56:in `perform'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/cli.rb:227:in `test'
D      /home/mmw/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /home/mmw/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/cli.rb:321:in `invoke_task'
D      /home/mmw/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /home/mmw/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/bin/kitchen:13:in `block in <top (required)>'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/errors.rb:174:in `with_friendly_errors'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/bin/kitchen:13:in `<top (required)>'
D      /home/mmw/.gem/ruby/2.3.0/bin/kitchen:23:in `load'
D      /home/mmw/.gem/ruby/2.3.0/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [Is a directory @ rb_sysopen - /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id/hosts] on baseline-security-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `initialize'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `open'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `prepare_hosts'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:252:in `create_sandbox'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:63:in `call'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:478:in `block in action'
D      /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:477:in `action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:369:in `converge_action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `each'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:160:in `verify'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:189:in `block in test'
D      /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:185:in `test'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `public_send'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `run_action_in_thread'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [Is a directory @ rb_sysopen - /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id/hosts]
D      ----------------------
D      ------Backtrace-------
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `initialize'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `open'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:862:in `prepare_hosts'
D      /home/mmw/.gem/ruby/2.3.0/gems/kitchen-ansible-0.43.0/lib/kitchen/provisioner/ansible_playbook.rb:252:in `create_sandbox'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/provisioner/base.rb:63:in `call'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:478:in `block in action'
D      /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:477:in `action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:369:in `converge_action'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `each'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:160:in `verify'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:189:in `block in test'
D      /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/instance.rb:185:in `test'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `public_send'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:194:in `run_action_in_thread'
D      /home/mmw/.gem/ruby/2.3.0/gems/test-kitchen-1.9.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

The main error appears to be 

```D      Message: Failed to complete #converge action: [Is a directory @ rb_sysopen - /tmp/baseline-security-ubuntu-1604-sandbox-20160803-9994-at23id/hosts] on baseline-security-ubuntu-1604```

However, the directory does not even appear to be created if you SSH on to the box.

I've hacked the code to prevent the cleanup operation from occurring, however, even then the directory still doesn't exist, leading me to believe that it has never even been created.

Has anyone seen this before?

**Comment by neillturner** [comment]
It doesn't like 
  roles_path: ../
i'm not sure if .. will work. 
just need to try some combinations.

**Comment by neillturner** [comment]
closing this as i don't support this so of role_path parameter.

**Comment by proffalken** [comment]
Thanks @neillturner you were spot on.

I'm sure I had it working before, but maybe that was something else!

for future reference, `role_path: <%= ENV['WORKSPACE'] %>/roles` allows you to easily use a single `~/.kitchen/config.yml` file with multiple repos just by setting the `WORKSPACE` environment variable :)

**Comment by neillturner** [comment]
thanks i've added this to the tips in the readme.
