### ISSUE TITLE
Bug: Could not load the 'kitchen-ansible' provisioner

### ISSUE THREAD

**Issue by juju4** [neillturner/kitchen-ansible#212]
seems similar to https://github.com/neillturner/kitchen-ansible/issues/162
It's a fresh install inside a lxc container (non-privileged) on Xenial host.

net-ssh or file permissions don't seem at fault. so where?

Thanks

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
# gem list

*** LOCAL GEMS ***

artifactory (2.5.0)
bigdecimal (1.2.8)
busser (0.7.1)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
io-console (0.4.5)
json (1.8.3)
kitchen-ansible (0.45.4)
kitchen-docker (2.6.0)
kitchen-lxd_cli (2.0.1)
kitchen-sync (2.1.1)
kitchen-vagrant (0.20.0)
kitchen-verifier-serverspec (0.6.0)
minitest (5.8.4)
mixlib-install (2.1.5)
mixlib-shellout (2.2.7)
mixlib-versioning (1.1.0)
multi_json (1.12.1)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (3.2.0)
net-ssh-gateway (1.2.0)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.0.17)
rake (10.5.0)
rdoc (4.2.1)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
safe_yaml (1.0.4)
serverspec (2.37.2)
sfl (2.3)
specinfra (2.63.3)
test-kitchen (1.13.2)
test-unit (3.1.7)
thor (0.19.0)
# cat .kitchen.yml 
---
driver:
  name: vagrant

provisioner:
  name: kitchen-ansible

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
# kitchen diagnose --all
---
timestamp: 2016-10-28 18:12:10 UTC
kitchen_version: 1.13.2
plugins:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'kitchen-ansible' provisioner
      from the load path. Please ensure that your provisioner is installed as a gem
      or included in your Gemfile if using Bundler.>"
    message: Could not load the 'kitchen-ansible' provisioner from the load path.
      Please ensure that your provisioner is installed as a gem or included in your
      Gemfile if using Bundler.
    backtrace:
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner.rb:48:in
      `rescue in for_plugin'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner.rb:40:in
      `for_plugin'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:290:in `new_provisioner'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:252:in `new_instance'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:144:in `block
      in build_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `map'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `with_index'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `build_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:119:in `instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:115:in
      `filtered_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:145:in
      `parse_subcommand'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:56:in `perform'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:142:in `diagnose'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:334:in `invoke_task'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/bin/kitchen:13:in `block in <top
      (required)>'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/errors.rb:174:in `with_friendly_errors'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/bin/kitchen:13:in `<top (required)>'"
    - "/usr/local/bin/kitchen:23:in `load'"
    - "/usr/local/bin/kitchen:23:in `<main>'"
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/root/me/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: kitchen-ansible
      platforms:
      - name: ubuntu-14.04
      - name: centos-7.2
      suites:
      - name: default
        run_list: 
        attributes: 
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: kitchen-ansible
      platforms:
      - name: ubuntu-14.04
      - name: centos-7.2
      suites:
      - name: default
        run_list: 
        attributes: 
instances:
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'kitchen-ansible' provisioner
      from the load path. Please ensure that your provisioner is installed as a gem
      or included in your Gemfile if using Bundler.>"
    message: Could not load the 'kitchen-ansible' provisioner from the load path.
      Please ensure that your provisioner is installed as a gem or included in your
      Gemfile if using Bundler.
    backtrace:
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner.rb:48:in
      `rescue in for_plugin'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner.rb:40:in
      `for_plugin'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:290:in `new_provisioner'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:252:in `new_instance'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:144:in `block
      in build_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `map'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `with_index'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:143:in `build_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/config.rb:119:in `instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:115:in
      `filtered_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:145:in
      `parse_subcommand'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:56:in
      `load_instances'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:35:in
      `block in call'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:80:in
      `record_failure'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command/diagnose.rb:35:in
      `call'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:56:in `perform'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:142:in `diagnose'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/cli.rb:334:in `invoke_task'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'"
    - "/var/lib/gems/2.3.0/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/bin/kitchen:13:in `block in <top
      (required)>'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/errors.rb:174:in `with_friendly_errors'"
    - "/var/lib/gems/2.3.0/gems/test-kitchen-1.13.2/bin/kitchen:13:in `<top (required)>'"
    - "/usr/local/bin/kitchen:23:in `load'"
    - "/usr/local/bin/kitchen:23:in `<main>'"
# ls -l /var/lib/gems/2.3.0/gems/kitchen-ansible-0.45.4/
total 24
-rw-r--r-- 1 root root 7956 Oct 28 16:57 README.md
-rw-r--r-- 1 root root 1132 Oct 28 16:57 kitchen-ansible.gemspec
drwxr-xr-x 4 root root 4096 Oct 28 16:57 lib
-rw-r--r-- 1 root root 7669 Oct 28 16:57 provisioner_options.md
```

**Comment by neillturner** [comment]
hi, 
 provisioner name is: 
name: ansible_playbook
as per https://github.com/neillturner/kitchen-ansible/blob/master/README.md

**Comment by juju4** [comment]
Ah. sorry for stupid mistake...

**Comment by neillturner** [comment]
no worries....
