### ISSUE TITLE
Converge fails with empty ansible vault configuration

### ISSUE THREAD

**Issue by arlimus** [neillturner/kitchen-ansible#49]
If I don't configure any ansible vault parts in my kitchen, a deployment is currently crashing:

```
       Preparing ansible vault password
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [no implicit conversion of nil into String]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Backtracking this to:

```
E, [2015-05-11T22:37:35.437402 #2649] ERROR -- Kitchen: /var/lib/gems/2.0.0/gems/kitchen-ansible-0.0.14/lib/kitchen/provisioner/ansible_playbook.rb:372:in `basename'
E, [2015-05-11T22:37:35.437443 #2649] ERROR -- Kitchen: /var/lib/gems/2.0.0/gems/kitchen-ansible-0.0.14/lib/kitchen/provisioner/ansible_playbook.rb:372:in `tmp_ansible_vault_password_file_path'
E, [2015-05-11T22:37:35.437487 #2649] ERROR -- Kitchen: /var/lib/gems/2.0.0/gems/kitchen-ansible-0.0.14/lib/kitchen/provisioner/ansible_playbook.rb:647:in `prepare_ansible_vault_password_file'
```

Reference: https://github.com/neillturner/kitchen-ansible/blob/817fd5dbb5c439c7bb806a7089497398742e9043/lib/kitchen/provisioner/ansible_playbook.rb#L372

**Comment by arlimus** [comment]
Ah, I just missed: https://github.com/neillturner/kitchen-ansible/pull/48

**Comment by arlimus** [comment]
Closed as duplicate.
